config/routes.rb
Rails.application.routes.draw do
  
  root 'shallows#home'
  
  resources :codes do
    member do
      delete 'remove_editor'
      post 'add_editor'
    end
  end

  devise_for :users
  
  resources :users, only: [:update]
   
  resources :charges, only: [:new, :create]

end

app/models/amount.rb
class Amount
  def self.default
    15_00
  end
end

app/models/code.rb
class Code < ActiveRecord::Base
  
  has_and_belongs_to_many :users, join_table: "editors"
  
  def private?
    private == true
  end
  
  def public?
    private == false
  end

end

app/models/editor.rb
class Editor < ActiveRecord::Base
  belongs_to :code
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  after_initialize :init
  
  has_and_belongs_to_many :codes, join_table: "editors"
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  def upgrade
    self.update_attribute(:role, "premium")
  end
  
  def downgrade
    self.update_attribute(:role, "standard")
  end
  
  
  def admin?
    role == 'admin'
  end
 
  def standard?
    role == 'standard'
  end
  
  def premium?
    role == 'premium'
  end
  
  def init
    self.role ||= 'standard'           #will set the default value only if it's nil
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include Pundit
  
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authorized
    if current_user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    else
      flash[:alert] = "Please Login"
      redirect_to new_user_session_path
    end
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def create
 
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
  charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Billqu Upgrade",
     currency: 'usd'
   )
   
   current_user.upgrade
   redirect_to root_path, success: "Thanks for all the money Feel free to pay me again."
  
    
 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
  
 end


def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Billqu - Membership",
    amount: Amount.default
  }
end
  
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  def index
    if current_user
      @codes = policy_scope(Code)
    else
      @codes = Code.where(private: false)
    end
  end

  def show
    @code = Code.find(params[:id])
    authorize @code
  end

  def new
    @code = Code.new
    authorize @code
  end
  
  def create
    @code = Code.new(code_params)
    @user = current_user
    authorize @code
    if @code.save
      if @user.admin? || @user.premium?
        @code.users << @user
      end
      redirect_to @code, notice: "Code was added succesfully"
    else
      flash[:error] = "Error creating Code"
      render :new
    end
  end

  def edit
    @code = Code.find(params[:id])
    authorize @code
    @users = @code.users
  end
  
  def update
    @code = Code.find(params[:id])
    authorize @code
    if @code.update_attributes(code_params)
      redirect_to @code
    else
      flash[:error] = "Error saving Code. Please try again"
      render :edit
    end
  end
  
  def destroy
    @code = Code.find(params[:id])
    title = @code.title

    authorize @code
    if @code.destroy
      redirect_to codes_path, notice: "\"#{title}\" was deleted successfully"
    else
      flash[:error] = "Could not delete Code"
      render :show
    end
  end
  
  def remove_editor
    @code = Code.find(params[:id])
    @user = User.find(params[:format])
    @code.users.delete(@user)
    redirect_to edit_code_path(@code)
  end
  
  def add_editor
    @code = Code.find(params[:id])
    @user = User.where(email: params[:email])
    
    if @user.empty?
      redirect_to edit_code_path(@code), alert: "User Not Found"
    elsif @code.users.include?(@user)
      redirect_to edit_code_path(@code), alert: "Editor already added"
    else
      @code.users << @user
      redirect_to edit_code_path(@code), notice: "Editor added succesfully"
    end
  end
  
  private
  
  def code_params
    params.require(:code).permit(:title, :body, :private, :user_id)
  end
  
end

app/controllers/shallows_controller.rb
class ShallowsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def update
    current_user.downgrade
    redirect_to edit_user_registration_path
    flash[:notice] = "Successfully Downgraded"
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/shallows_helper.rb
module ShallowsHelper
end

app/views/charges/new.html.erb
<div class="container">
  <div class="row text-center">
     <%= form_tag charges_path do %>
       <h4>Click the button!</h4>
       <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
             data-key="<%= @stripe_btn_data[:key] %>" 
             data-amount=<%= @stripe_btn_data[:amount] %> 
             data-description="<%= @stripe_btn_data[:description] %>"> 
      </script>
   <% end %>
  </div>
</div>

app/views/codes/_code.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= link_to code.title, code %>
    </div>
  </div>
</div>
  

app/views/codes/_new_editor.html.erb
<%= form_tag(add_editor_code_path, method: "post") do %>
<%= label_tag(:email, "Enter Email") %>
<%= text_field_tag(:email) %>
<%= submit_tag("Add Editor") %>
<% end %>

app/views/codes/edit.html.erb
<div class="container">
  <div class="header">
    <h2><%= @code.title %></h2>
  </div>
</div>
<div class="container">
  <%= form_for @code do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: markdown_to_html(@code.title) %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 20, class: 'form-control', placeholder: markdown_to_html(@code.body) %>
      </div>
      <div class="form-group">
        <% if current_user.standard? %>
          <%= link_to "Upgrade to Premium!", edit_user_registration_path, class: 'btn btn-lg btn-info' %>
        <% else %>
          <div class="row">
            <div class="col-md-4 offset-2"
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box("private") %> Private Code
            <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="form-group">
           <%= f.submit "Save", class: 'btn btn-success btn-large' %>
      </div>
    <% end %>
</div>

<% if @code.users.include?(current_user) || current_user.admin? %>
  <div class="container">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#editors" aria-expanded="false" aria-controls="editors">
      Change Collaborators
    </button>
    <div class="collapse" id="editors">
      <div class="well">
        <table class="table table-bordered">
          <th>User Email</th>
          <th>Remove User</th>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= link_to "Remove User", remove_editor_code_path(@code, user), method: :delete %></td>
          </tr>
          <% end %>
        </table>
      </div>
      <%= render "new_editor" %>
    </div>
</div>
<% end %>

app/views/codes/index.html.erb
<div class="container">
  <div class="header">
    <h2>Billing Codes</h2>
  </div>
</div>
<%= render @codes || "No Codes in the Database" %>

app/views/codes/new.html.erb
<div class="container">
  <div class="header">
    <h2>New Code</h2>
  </div>
</div>
<div class="container">
  <%= form_for @code do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter Code" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 25, class: 'form-control', placeholder: "Body" %>
    </div>
    <div class="form-group">
      <% if current_user.standard? %>
        <%= link_to "Upgrade to Premium!", edit_user_registration_path, class: 'btn btn-lg btn-info' %>
      <% else %>
        <%= f.label :private %>
        <%= f.check_box :private %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "Save Code", class: 'btn btn-success btn-lg' %>
    </div>
  <% end %>
</div>

app/views/codes/show.html.erb
<div class="container">
  <div class="header">
    <h2><%= markdown_to_html @code.title %></h2>
  </div>
</div>
<div class="container">
  <p> 
    <%= markdown_to_html @code.body %>
  </p>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= link_to "Edit Code", edit_code_path, class: 'btn btn-default' %>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete Code", @code, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delte this Code?'} %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <title>Billqu</title>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to( "Billqu", root_path, html_options = {class: "navbar-brand"}) %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Codes <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "All Codes", codes_path %></li>
                <li><%= link_to "Add New Code", new_code_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li> <%= link_to current_user.email, edit_user_registration_path(current_user) %> </li>
            <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li> <%= link_to "Sign In", new_user_session_path %></li>
            <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <div class="container alrts">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
       <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:success] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    </div>

    <!-- Begin page content -->
    <%= yield %>

    <footer class="footer">
      <div class="container">
      </div>
    </footer>

    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

  </body>
</html>

app/views/shallows/home.html.erb
<div class="container">
  <div class="page-header">
    <div class="row text-center">
      <%= image_tag("logo2.png" ) %>
    </div>
  </div>
</div>
<div class="container" id="home-page">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1>Billqu</h1>
      <hr class="star-light">
    </div>
  </div>
    <div class="row">
      <div class="col-lg-4 col-lg-offset-2">
        <p>Billqu is a way to share information about medical bills. Understanding to empower your ability as a medical consumer</p>
      </div>
      <div class="col-lg-4">
        <p>Reasearch and understand your bills. Share your knowlege with other users</p>
      </div>
  </div>
</div>           